name: news_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  conditional_builder_null_safety: ^0.0.6
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  dio: ^5.0.3
  webview_flutter: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
